#pragma once
#include <vector>
#include <random>

class Arm // Creation of an Arm
{
public:
	Arm(void);
	~Arm(void);
	virtual double Generate(std::mt19937_64& generator) = 0; // Virtual method, depends on the type of the arm
	double GetRealMean(); // returns the mean of the arm's distribution
	double GetEmpiricalMean();// returns the empirical mean of the arm
	int GetTimesChosen();// returns the number of times the Arm has been chosen
protected:
	int _timesChosen;// number of times the Arm has been chosen
	std:: vector <double> _history; //history of the rewards generated by the arm
	std:: vector <double> _parameter;//parameters of the distribution
	double _mean;//mean of the distribution
};

